version: 2.1
orbs:
  win: circleci/windows@2.4.1
jobs:
  build:
    executor:
      name: win/default
      shell: cmd.exe
    steps:
      - checkout
      - run:
          name: "Build"
          command: "msbuild UE4TextExtractor.sln -p:Configuration=Release"
      - run:
          name: "Test"
          command: "cd tests && call __run.bat"
      - run:
          name: "Check"
          command: "for /f %i in ('git status --porcelain') do (exit /b 1)"
